### PR TITLE
New look of the page 'Carry'

### PR DESCRIPTION
**Pull request by Marvizm**
ynl

### CODE REVIEW

**Comment by howardchung** [comment]
@albertcui to review.

Do we have attribution/permission to use the image?

**Comment by Marvizm** [comment]
@howardchung actually Idk :D, this is the loading screen http://dota2.gamepedia.com/Top_Lane_(Loading_Screen)

**Comment by howardchung** [comment]
I think we need to make sure we have permission to use it before we deploy

**Comment by albertcui** [comment]
Changes look good to me, but we've be running a policy of only using assets that we have explicit permission for. So for this to be mergeable we'd probably need another picture, or at least permission. Also, what do you think about adding some dark overlay or text shadow in the "YASP is completely..." over the picture? Since the image is kind of white it gets harder to read on the right side.

**Comment by Marvizm** [comment]
@howardchung, @albertcui, I found this https://steamcommunity.com/discussions/forum/12/527273452880775596/ and this http://www.valvesoftware.com/legal.html, I think image can be used, but maybe need to add: 
image because on [dota2.gamepedia.com](http://dota2.gamepedia.com/Top_Lane_(Loading_Screen)) writen Created By Perfect World,if you do not think so, nothing prevents to find another image
P.S sorry if I make mistakes, I speak English horribly, but I try to get better :P

**Comment by Marvizm** [comment]
I found the author of this image in [Steam workshop](http://steamcommunity.com/sharedfiles/filedetails/?id=235195874), I will ask him about permission.

**Comment by Marvizm** [comment]
image
got permission from author to use picture

**Comment by albertcui** [comment]
Awesome! Thanks!

**Pull request merged**
