### PR TITLE
Change Item Active detection

### PR DESCRIPTION
**Pull request by WTFKr0**
Adds ring_of_aquila, ring_of_basilius and linken's shpere to Active items
Signed-off-by: WTFKr0 <thomas.kovatchitch@gmail.com>

### CODE REVIEW

**Comment by howardchung** [comment]
Do we expect players to use those items at least once?

**Comment by WTFKr0** [comment]
Yeah, that's a good question !
Linken maybe ?
It's like Quelling Blade / Battle Fury / Mjollnir : don't need to be used systematically

**Comment by howardchung** [comment]
@albertcui ?

I'm fine with it either way

**Comment by albertcui** [comment]
Fine with me. Thanks!

**Pull request merged**
