### PR TITLE
use java thread pool

### PR DESCRIPTION
**Pull request by howardchung**
Thread pool to allow multiple parallel requests on parseserver

### CODE REVIEW

**Comment by gortiz** [comment]
Why not use a cached thread pool?

**Comment by howardchung** [comment]
what is the advantage?

**Comment by gortiz** [comment]
A cached thread executor pool has as many threads as necessary. Once a
thread finished its task, it waits a fixed number of seconds for a new one.
If there is no new task, the thread is destroyed. The main problem this
executor has is that it can potentially generate too many threads.

You could also try to use a ForkJoinPool but, to be honest, the more I
think about your use case, the more I would opt for FixedThreadPool, as it
is the simplest way to do it.

2016-07-26 11:26 GMT+02:00 Howard Chung <notifications@github.com>:

**Comment by howardchung** [comment]
Yeah, that's why I opted for the fixed pool (to avoid the potential problem of creating too many threads).  In practice, we control exactly how hard we hit the parse server (current parallelism of parse jobs is 2), so I think both would work fine.

**Pull request merged**
