### PR TITLE
Fixed application crash in /status if PostgreSQL connection is lost.

### PR DESCRIPTION
**Pull request by mhartkorn**
yasp crashes if there is no connection to PostgreSQL. This could happen if the SQL server crashes or goes down for maintenance.

The reason is that `count` is then undefined and has no attribute `rows`.

So far the commit displays a white page with a stacktrace. Might not be the most elegant way but the player pages behave the same way. Is there an easy way to make some pretty 500 error pages from the `status` module?

### CODE REVIEW

**Comment by mhartkorn** [comment]
I don't know why the Travis-CI check fails. The commit only has 3 lines which run perfectly fine here. `npm test` also works locally.

**Comment by howardchung** [comment]
looks like ENOSPC (you can view the log).  I did a rebuild

**Comment by howardchung** [comment]
signoff, @albertcui please review

**Comment by albertcui** [comment]
Thanks for the contribution!

**Pull request merged**
