### PR TITLE
damage_inflictor_received

### LINKED ISSUE #903: Request parse of damage received.
A useful feature is the biggest hit feature, but the team and I often try to imagine the sources of the damage our hero has received and where the biggest source of damage is coming from. So perhaps we could have a feature that shows the amount of damage taken and have it split between what damaged us.

Eg. If a bristleback is focused - it would be nice to see how much damage he was able to soak up for the team.

### PR DESCRIPTION
**Pull request by howardchung**
fixes #903 

## Deployment
- [x] update cassandra schema `ALTER TABLE player_matches add damage_inflictor_received text;`

Reviewers:
@albertcui 
@mm11wils

Scheduled release:
2016-06-03?

### CODE REVIEW

**Comment by don4of4** [comment]
Just a friendly tip:  it might be worth reviewing and making use of interactive rebasing for this project, it would help keep the commit log cleaner.

https://www.atlassian.com/git/tutorials/rewriting-history/

**Comment by howardchung** [comment]
Thanks for the tip.  I agree it's kind of messy

**Comment by howardchung** [comment]
Tried to rebase, hopefully I did it right :)

**Comment by don4of4** [comment]
Generally an interactive rebase requires a force push and should be done on a local/user branch.  Now, I do not see any changes here, so I don't think you managed to push anything.

**Comment by howardchung** [comment]
It went from 14 commits down to 9?  I suppose it could be squashed down to 1.

(I did do a force push)

**Comment by don4of4** [comment]
Oh... You should def. squash commits which are called "undo" etc.

**Pull request merged**
