### PR TITLE
Add message for players who abandoned the match.

### LINKED ISSUE #886: 'Abandoned' flagging
When showing a match, Dotabuff puts a little 'abandoned' note near a player's name if they abandoned it.

Is is possible to do something similar in Yasp?

### PR DESCRIPTION
**Pull request by JazzyJosh**
fixes #886 

Addresses yasp-dota/yasp#886

### CODE REVIEW

**Comment by JazzyJosh** [comment]
@howardchung I know you assigned this to yourself, but I wanted to get my environment running anyway. Feel free to decline if you've already fixed this.

**Comment by howardchung** [comment]
I haven't, thanks for looking at this.

* Looks like you forgot to include the change to hero_td mixin.
* Since you're checking a property on player anyway, check it within hero_td instead of passing a param to hero_td.

**Comment by JazzyJosh** [comment]
I didn't make any changes to the mixin. I reused it the same way that match_index was, unless I'm missing something.

I could refactor those usages to separate mixins or just allow hero_td to have a block following it. I assume the first option would be preferred.

**Comment by howardchung** [comment]
ah I see you're reusing the metadata field.

I think it's fine to show up only on the index page.

Looks okay to me, @albertcui please review.

**Comment by albertcui** [comment]
Looks good to me. Thanks!

**Pull request merged**
