### PR TITLE
Played with

### PR DESCRIPTION
**Pull request by evaldobratti**
This is a WIP.
I have opened a request ages ago #651 about a easier way to find who we already played with.
I have already developed my own website for hobby (http://dotaparty.me/), but since I'm not going to pay more that I already pay for hosting services, I tryed to develop this functionality on yasp.
I have created a new tab on details match that show directly whom players have already played with.
It does not need any data migration, it's just a raw sql (so, there is one extra query when loading matches) .
I newbie on node and all its environment, so any feedback is appreciated.
It is still lacking tests, but I'll study and create them if this fuctionality is of your interest.

### CODE REVIEW

**Comment by howardchung** [comment]
Considerations:

* I don't think this approach will scale.  Currently it looks like you're querying for all matches of about 10 players (twice), then counting the number of unique pairs encountered.  Based on the fact that it takes roughly 10-30 seconds to query for just one player's matches, this query will take minutes to run on production.
* We are moving data out of postgres and into cassandra, so this table won't exist anymore in a week or so.

* Potential alternate solution: Perhaps you can utilize the peers data for each player (https://yasp.co/api/players/88367253/peers).  That's still making 10 requests per match, though.

**Comment by evaldobratti** [comment]
So, this feature could be added to yasp?

I've found some cassandra references in the code, but I thought the schema would almost be the same, I'll review the code to make it work on cassandra.
About the peers code, I studied it and maybe I have missed something, It seemed that all player matches was load and then the aggregation was make, is my understanding right?

If I use the api, it would be better to load data via ajax on client and fill the table as it loads, or render all the page on server?
Thank you :)

**Comment by howardchung** [comment]
Cassandra does not support joins so you might not be able to do it the same way.

The peers page is now served out of a third table called "player_caches".  It is much faster to load a player's matches from this collection.

We are currently in the process of developing the new UI (see https://github.com/yasp-dota/ui), which is React-based and will use API endpoints on the server for everything.  If you want to implement this you should make it return as an endpoint and then work in that repo to build the UI for it.

Depending on how slow the query is, you may need to separate it from the match endpoint since that must load quickly for a good user experience.

**Comment by evaldobratti** [comment]
I see, I'll checkout this new UI and problably, make it only available on it. I'll problably make a new endpoint and load it dynamically por each player, cus, as you said, it'll take about 10 queries to fill all the table.

Running yasp locally it's not fetching players data (as personaname and avatar), what could be missing?

**Comment by howardchung** [comment]
Player data is not in matches.  It needs to be obtained from a separate endpoint (see `svc/profiler.js`).

Or you can manually fake some data

**Comment by evaldobratti** [comment]
I'll check it later.
It's throwing 
```
...
 [299] ./~/font-awesome/css/font-awesome.css 1.21 kB {0} [built] [1 error]
...

ERROR in ./~/css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]d!./~/postcss-loader!./~/font-awesome/css/font-awesome.css
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/home/evaldo/codes/ui/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/home/evaldo/codes/ui/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:79:21)
    at Object.module.exports (/home/evaldo/codes/ui/node_modules/postcss-loader/index.js:63:10)
 @ ./~/font-awesome/css/font-awesome.css 4:14-179
```
when starting the new ui, any clues?
You can close this PR then

**Comment by howardchung** [comment]
Check your node version and upgrade, most likely

**Comment by evaldobratti** [comment]
Ok, thank you for your support :+1:

**Comment by gu3st** [comment]
I think you need to upgrade your node version to at least v5, preferably v6 (as the UI, we are using pretty bleeding edge stuff like the spread operator)

**Comment by evaldobratti** [comment]
I tried with node 6.2.0 and it did not work. On node 5.11.1 it seems ok. It is just basic html, with no css by now, right?

**Comment by howardchung** [comment]
Try pulling latest master, I fixed a bug with it not working on 6.2.0 a few hours ago.

No CSS yet, we just started a few days ago

**Pull request closed without merging**
