### PR TITLE
fix wrong link ?

### PR DESCRIPTION
**Pull request by Marvizm**
screen

### CODE REVIEW

**Comment by howardchung** [comment]
thanks, I missed some spots.

@albertcui please review.

**Comment by howardchung** [comment]
one more if you don't mind:
https://github.com/yasp-dota/yasp/blob/master/views/player/player_records.jade#L77

**Comment by howardchung** [comment]
Signoff

**Comment by howardchung** [comment]
@albertcui if you merge this please also trigger a manual web deployment

**Comment by albertcui** [comment]
Great, thanks!

**Pull request merged**
